version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data_container:/data/   

volumes:
  mongodb_data_container:
  redis_data_container: