name: Deploy Report & Coverage Testing to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword  
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the appropriate Node.js version for your project

      - name: Copy .env.pipeline to .env
        run: cp .env.pipeline .env

      - name: Wait for MongoDB and Redis to be ready
        run: |
          while ! nc -z localhost 27017; do
            sleep 1
          done
          while ! nc -z localhost 6379; do
            sleep 1
          done

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test

      - name: Run tests and generate coverage report
        run: npm run test:cov:html
   

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          publish_dir: ./testing  # Directory with the generated coverage report
          publish_branch: gh-pages  # Branch to deploy to (GitHub Pages branch)


  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Add a comment on the pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          script: |
            const url = `https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/coverage`;
            const url2 = `https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/`;

            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The coverage report has been deployed to: [${url}](${url}) and [${url2}](${url2})`
            });